#!/bin/bash
#
# Copyright (c) 2016 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

#
# This script provides an example in-service patching restart,
# triggering a restart of the patching daemons themselves
#

#
# The patching subsystem provides a patch-functions bash source file
# with useful function and variable definitions.
#
. /etc/patching/patch-functions

#
# We can now check to see what type of node we're on, if it's locked, etc,
# and act accordingly
#

#
# Declare an overall script return code
#
declare -i GLOBAL_RC=$PATCH_STATUS_OK


# Vim only runs on the controller

if is_controller
then
    processes_to_restart="nfv-vim nfv-vim-api nfv-vim-webserver"
    /usr/local/sbin/patch-restart-processes ${processes_to_restart}
    if [ $? != 0 ] ; then
        loginfo "patching restart failed"
        loginfo "... process-restart ${processes_to_restart}"
        GLOBAL_RC=$PATCH_STATUS_FAILED
    fi
fi


#
# Exit the script with the overall return code
#
exit $GLOBAL_RC

