---
- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - openstack-tox-linters
        - openstack-tox-pep8
        - openstack-tox-py27
        - openstack-tox-py35
        - stx-updates-pylint
        - stx-devstack-update:
            voting: false
    gate:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - openstack-tox-linters
        - openstack-tox-pep8
        - openstack-tox-py27
        - openstack-tox-py35
        - stx-updates-pylint
    post:
      jobs:
        - publish-stx-api-ref
        - publish-stx-tox
        - publish-stx-releasenotes

- job:
    name: stx-updates-pylint
    parent: openstack-tox-pylint
    required-projects:
      - openstack/stx-config
      - openstack/stx-fault
      - openstack/stx-integ

- job:
    name: stx-devstack-update
    parent: stx-devstack-base
    timeout: 7800
    required-projects:
      - openstack/stx-fault
    vars:
      tox_envlist: functional
      devstack_services:
        # Cinder services
        c-api: false
        c-bak: false
        c-sch: false
        c-vol: false
        cinder: false
        # Glance services
        g-api: false
        g-reg: false
        # Nova services
        n-api: false
        n-api-meta: false
        n-cauth: false
        n-cond: false
        n-cpu: false
        n-novnc: false
        n-obj: false
        n-sch: false
        placement-api: false
        # Neutron services
        q-agt: true
        q-dhcp: false
        q-l3: false
        q-meta: false
        q-metering: false
        q-svc: false
        horizon: false
        # StarlingX services
        sw-patch: true
        tsconfig: true
      devstack_plugins:
        stx-fault: git://git.starlingx.io/stx-fault
        stx-update: git://git.starlingx.io/stx-update
      devstack_localrc:
        LIBS_FROM_GIT: keystone
    files:
      - ^devstack/.*
