---
- project:
    check:
      jobs:
        - openstack-tox-linters
        - openstack-tox-pep8:
            voting: false
        - stx-updates-pylint
    gate:
      jobs:
        - openstack-tox-linters
        - stx-updates-pylint

- job:
    name: stx-updates-pylint
    parent: openstack-tox-pylint
    required-projects:
      - openstack/stx-config
      - openstack/stx-fault
      - openstack/stx-integ
