---
- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - build-openstack-releasenotes
        - openstack-tox-linters
        - openstack-tox-pep8
        - stx-updates-pylint
    gate:
      jobs:
        - build-openstack-releasenotes
        - openstack-tox-linters
        - openstack-tox-pep8
        - stx-updates-pylint
    post:
      jobs:
        - publish-stx-api-ref
        - publish-stx-tox
        - publish-stx-releasenotes

- job:
    name: stx-updates-pylint
    parent: openstack-tox-pylint
    required-projects:
      - openstack/stx-config
      - openstack/stx-fault
      - openstack/stx-integ
