---
- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - flock-devstack-update
        - openstack-tox-linters
        - openstack-tox-pep8
        - openstack-tox-py27
        - openstack-tox-py37
        - stx-updates-pylint
    gate:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - flock-devstack-update
        - openstack-tox-linters
        - openstack-tox-pep8
        - openstack-tox-py27
        - openstack-tox-py37
    post:
      jobs:
        - publish-stx-api-ref
        - publish-stx-tox
        - publish-stx-releasenotes

- job:
    name: stx-updates-pylint
    parent: openstack-tox-pylint
    required-projects:
      - openstack/stx-config
      - openstack/stx-fault
      - openstack/stx-integ

- job:
    name: flock-devstack-update
    parent: flock-devstack-base-min
    required-projects:
      - openstack/stx-integ
    vars:
      tox_envlist: functional
      devstack_services:
        # StarlingX services
        sw-patch: true
        tsconfig: true
      devstack_plugins:
        stx-integ: https://git.starlingx.io/stx-integ
        stx-update: https://git.starlingx.io/stx-update
