#!/bin/bash
#
# Copyright (c) 2016 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

#
# This script provides an example in-service patching restart,
# triggering a restart of the patching daemons themselves
#

#
# The patching subsystem provides a patch-functions bash source file
# with useful function and variable definitions.
#
. /etc/patching/patch-functions

#
# We can now check to see what type of node we're on, if it's locked, etc,
# and act accordingly
#

#
# Declare an overall script return code
#
declare -i GLOBAL_RC=$PATCH_STATUS_OK

#
# First up, we'll handle restarting the patch-agent, which runs on all nodes
# Since the patch-agent is a delayed restart, there's no error to return
#
/usr/sbin/sw-patch-agent-restart

#
# Next, handle restarting the patch-controller.
#
if is_controller
then
    /usr/sbin/sw-patch-controller-daemon-restart
fi


#
# Exit the script with the overall return code
#
exit $GLOBAL_RC

