#!/bin/bash
#
# Copyright (c) 2016 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

#
# This script provides config file update during in-service patching
#

#
# The patching subsystem provides a patch-functions bash source file
# with useful function and variable definitions.
#
. /etc/patching/patch-functions

#
# Declare an overall script return code
#
declare -i GLOBAL_RC=$PATCH_STATUS_OK

cp -f /tmp/nfsmount.conf /etc/
chmod 644 /etc/nfsmount.conf
echo "nfsmount.conf copied to system folder successfully"
#
# Exit the script with the overall return code
#
exit $GLOBAL_RC

