#!/bin/bash
# Devstack settings

# Defaults
# --------

STX_UPDATE_NAME=stx-update

######### Plugin Specific ##########
enable_service $STX_UPDATE_NAME
#define_plugin $STX_UPDATE_NAME

# Initial source of lib script
source $DEST/stx-update/devstack/lib/stx-update
